### ISSUE TITLE
status of std.io

### ISSUE THREAD

**Issue by greenify** [schveiguy/iopipe#1]
Hey I have seen that a couple of years ago you planned this module to be part of phobos. Judging from the feedback, it seems that you might have enough support behind this. Do you plan to submit it again for review / voting? :)

> Steven, this is superb!
> Some 10+ years ago, I talked to Tango guys when they worked on I/O part of the Tango library and told them that in my head ideal abstraction for any I/O work is pipe and that I would actually build an I/O library around this abstraction instead of the Channel in Java or Conduit in Tango (well, we all know Tango borrowed ideas from Java API).
> Your work is precisely what I was talking about. Well-done!

**Comment by schveiguy** [comment]
Thanks for the question. At this time I'm not worried about that. The message you posted which I did see is from someone who is an old-timer in D land, but not one of the main developers/maintainers of D/Phobos. I have not heard any such positive feedback from the main developers, in fact mostly silence.

I want to see how far I can push this as its own project before attempting to replace or amend Phobos i/o. Yes, it would be nice to get this in there, but I hope to at least have something more meaty before doing that. It significantly lowers the bar of acceptance for this project if it's known that this isn't threatening anyone's existing code :)

I don't expect it to take off until I have some more interesting results. Right now, just the toy examples aren't enough. I fully expect this library to be transformative, as thinking about i/o in a buffer sense frees up so much potential for performance.

**Comment by schveiguy** [comment]
Note, I'm closing this as it isn't really an issue :)
