### ISSUE TITLE
Builds failing with v0.2.0 - std.io not retrieved

### ISSUE THREAD

**Issue by jondegenhardt** [schveiguy/iopipe#30]
Hi Steve,

Congrats on getting the new @safe version out. Good to see progress here.

I ran my weekly cron job on dcat-perf which uses iopipe. It failed, it appears that `std.io` is no longer automatically pulled as a dependency. The builds are travis-ci.com, [here](https://travis-ci.com/github/jondegenhardt/dcat-perf/builds/172960136).

The only thing I could find is this commit: [Make dependency on io optional...](https://github.com/schveiguy/iopipe/commit/576ad32b569daaa26d6f3232c9f8cff08df666ee#diff-406ece895a5b70a272cd76a2ef902836). It added the `optional=true` flag to the `dub.sdl` file.
```
dependency "io" version="~>0.2.4" optional=true
```

This commit was done a while ago, but from the git tags it appears that v0.2.0 is the first time it got tagged.

Is this something I should be changing in my `dub` config files (adding `std.io` as a dependency), or is this a dependency `iopipe` should take care of?

**Comment by schveiguy** [comment]
Yes, I forgot I did that. Technically, nothing in iopipe depends on std.io except `openDev` (which is deprecated). 

You should definitely depend on `io` and then `openDev` becomes available, but still deprecated (see here: https://github.com/schveiguy/iopipe/blob/d38b289d4527647ecc05f22eccae6f1f79ab3e6d/source/iopipe/stream.d#L10).

**Comment by schveiguy** [comment]
Updated, try 0.2.1.
