### ISSUE TITLE
Register on DUB (and make first git-tagged release)

### ISSUE THREAD

**Issue by wilzbach** [schveiguy/iopipe#4]
It would be very handy if one could depend on `iopipe` with DUB. This also has the advantage that examples are then universally executable, e.g.

```d
#!/usr/bin/env dub
/+ dub.sdl:
name "iopipe_example"
dependency "iopipe" version="~>0.0.1"
+/
```

For this to work you also need to `git tag` a first release.

**Comment by schveiguy** [comment]
It's now added.
